<template>
    <div class="popup-content">
        <x-header slot="header" :left-options="{showBack:false}">
            用户注册协议
            <span class="iconfont icon-fanhui" slot="left" @click="onBack"></span>
        </x-header>
        <div style="padding: 0 .1rem;background-color: #fff">
            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt; font-weight:bold">&nbsp;</span>
            </p>
            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:11pt">淘不锈用户注册协议（以下简称</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">“</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本协议</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">”</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">）是您与淘不锈电商平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">（</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">以下简称</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">”</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">”</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">，</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">包括但不限于手</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">机</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">App</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">、</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">）所有者江苏淘不锈电子商务有限公司（以下简称为</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">”</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">淘不锈</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">”</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">）之间就</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">规定和</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">服务等相关事宜所订立的契约，请您仔细阅读本协议，</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">在</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">您</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">同意本协议</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">后，本协议即构成对双方有约束力的法律文件。</span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">&nbsp;</span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">第</span><span style="font-family:Helvetica; font-size:12pt; font-weight:bold">1</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">条</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:bold"> </span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">服务条款的确认和接纳</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:bold"> </span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">1.1</span><span style="font-family:Helvetica; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">的各项在线服务的所有权和运作权归</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">所有。用户同意所有注册协议条款并完成注册程序，才能成为</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">的正式用户。用户确认：本协议条款是处理双方权利义务的契约，始终有效，法律另有强制性规定或双方另有特别约定的，依其规定。</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">1.2</span><span style="font-family:Helvetica; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">用户</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">同意</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本协议，即视为用户确认自己具有享受在线购买不锈钢产品及享受服务等相应的权利和行为能力，能够独立承担法律责任。</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">1.3</span><span style="font-family:Helvetica; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">保留在中华人民共和国大陆地区法施行之法律允许的范围内独自决定拒绝服务、关闭用户账户、清除或编辑内容或取消订单的权利。</span>
            </p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">&nbsp;</span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">第</span><span style="font-family:Helvetica; font-size:12pt; font-weight:bold">2</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">条</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:bold"> </span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">服务</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:bold"> </span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">2.1</span><span style="font-family:Helvetica; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">通过互联网依法为用户提供不锈钢产品信息等服务，用户在完全同意本协议及</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">规定的情况下，方有权使用</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">的相关服务。</span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">&nbsp;</span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">第</span><span style="font-family:Helvetica; font-size:12pt; font-weight:bold">3</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">条</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:bold"> </span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">用户信息</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:bold"> </span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">3.1</span><span style="font-family:Helvetica; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">用户必须是具有完全民事行为能力的自然人。用户应本着个人或企业诚信向</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">提供真实、准确、完整、合法有效的注册资料。如果用户提供的注册资料不合法有效、不真实、不准确、不详尽的，用户需承担因此引起的相应责任及后果，并且</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">保留终止用户使用</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">各项服务的权利。用户注册资料如有变动的，应及时到</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">更新其注册资料，并承担因未及时通知</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">而作相应变更所导致的责任及后果</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">。</span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">&nbsp;</span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">3.2</span><span style="font-family:Helvetica; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">用户在</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">进行浏览、下单</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">等活动时，涉及用户及企业真实姓名</span><span style="font-family:Helvetica; font-size:11pt">/</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">名称、通信地址、联系方式、营业执照等隐私信息的，</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">将予以严格保密，除非</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">得到用户授权或法律另有规定，</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">将不会向</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">平台使用范围外</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">披露用户及企业隐私信息。</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">&nbsp;</span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">3.3</span><span style="font-family:Helvetica; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">用户注册成功后，将产生密码等账户信息，您可以根据</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">提示修改您的密码。用户应谨慎合理的保管、使用其账号及密码。用户若发现任何非法使用用户账号或存在安全漏洞的情况，请立即通知</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">。否则，由于用户自身的疏忽而导致账号信息泄露等后果，由用户自行承担。</span>
            </p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">&nbsp;</span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">3.4</span><span style="font-family:Helvetica; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">用户若将在</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">注册获得的账户借给他人使用，则必须承担由此产生的全部责任，且实际使用人需承担连带责任。</span>
            </p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">&nbsp;</span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">3.5 </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">用户同意，</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">拥有通过邮件、短信、电话等形式，向在</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">注册、购物的用户发送订单信息、促销活动等告知信息的权利。</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">&nbsp;</span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">3.6</span><span style="font-family:Helvetica; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">用户同意，</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">有权使用用户的注册信息、密码等信息，登陆进入用户的注册账户，进行证据保全，包括但不限于公证、见证等。</span>
            </p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">&nbsp;</span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">&nbsp;</span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">第</span><span style="font-family:Helvetica; font-size:12pt; font-weight:bold">4</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">条</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:bold"> </span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">用户依法言行义务</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:bold"> </span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:11pt">本协议依据国家相关法律法规规章制定，用户同意严格遵守以下义务：</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:11pt">（</span><span style="font-family:Helvetica; font-size:11pt">1</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">）不得传输或发表：煽动抗拒、破坏宪法和法律、行政法规实施的言论，煽动颠覆国家政权，推翻社会主义制度的言论，煽动分裂国家、破坏国家统一的的言论，煽动民族仇恨、民族歧视、破坏民族团结的言论；</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:11pt">（</span><span style="font-family:Helvetica; font-size:11pt">2</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">）从中国大陆向境外传输资料信息时必须符合中国有关法规；</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:11pt">（</span><span style="font-family:Helvetica; font-size:11pt">3</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">）不得利用</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">从事洗钱、窃取商业秘密、窃取个人信息等违法犯罪活动；</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:11pt">（</span><span style="font-family:Helvetica; font-size:11pt">4</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">）不得干扰</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">的正常运转，不得侵入</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">及国家计算机信息系统；</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:11pt">（</span><span style="font-family:Helvetica; font-size:11pt">5</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">）不得传输或发表损害国家社会公共利益和涉及国家安全的信息资料或言论；</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:11pt">（</span><span style="font-family:Helvetica; font-size:11pt">6</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">）不得教唆他人从事本条款所禁止的行为；</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:11pt">（</span><span style="font-family:Helvetica; font-size:11pt">7</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">）不得利用在</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">注册的账户进行非法牟利经营活动；</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">用户应不时关注并遵守</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">不时公布或修改的各类合法规则规定。</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">保有删除站内各类不符合法律政策或不真实的信息内容而无须通知用户的权利。</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">若用户未遵守以上规定的，</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">有权作出独立判断并采取暂停或关闭用户帐号等措施。用户须对自己在网上的言论和行为承担法律责任。</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">&nbsp;</span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">第</span><span style="font-family:Helvetica; font-size:12pt; font-weight:bold">5</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">条</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:bold"> </span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">商品信息</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:bold"> </span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">上的货物价格、数量、是否有货等商品信息将根据市场行情及</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">卖方</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">销售情况随时发生变动，</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">不作特别通知。由于</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">货物信息数量庞大，虽然</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">会尽最大努力保证您所浏览商品信息的准确性，但由于网络及电脑终端兼容性等客观原因存在，</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">网页显示的信息可能会有一定的滞后性或差错，对此情形请您知悉并理解；</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">欢迎纠错</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">。</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">&nbsp;</span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">第</span><span style="font-family:Helvetica; font-size:12pt; font-weight:bold">6</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">条</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:bold"> </span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">责任限制及不承诺担保</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:bold"> </span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:11pt">除非另有明确的书面说明</span><span style="font-family:Helvetica; font-size:11pt">,</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">及其所包含的或以其它方式通过</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">提供给您的全部信息、资料、货物（包括软件）和服务，均是在</span><span style="font-family:Helvetica; font-size:11pt">"</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">按现状</span><span style="font-family:Helvetica; font-size:11pt">"</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">和</span><span style="font-family:Helvetica; font-size:11pt">"</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">按现有</span><span style="font-family:Helvetica; font-size:11pt">"</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">的基础上提供的。</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">除非另有明确的书面说明</span><span style="font-family:Helvetica; font-size:11pt">, </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">淘不锈不对</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">的运营及其包含在本</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">上的信息、资料、货物（包括软件）和服务作任何形式的、明示或默示的声明或担保（根据中华人民共和国法律另有规定的以外）。</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">如因不可抗力或其它</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">无法控制的原因使</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">销售系统崩溃或无法正常使用导致网上交易无法完成或丢失有关的信息、记录等，</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">会合理地尽力协助处理善后事宜。</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">&nbsp;</span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:12pt">第</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:bold">7</span><span style="font-family:'Arial Unicode MS'; font-size:12pt">条</span><span style="font-family:'Arial Unicode MS'; font-size:12pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:12pt">协议更新及用户关注义务</span><span style="font-family:'Arial Unicode MS'; font-size:12pt"> </span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:11pt">7</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">.1 </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">根据国家法律法规变化及</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">运营需要，</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">有权对本协议条款不时地进行修改，修改后的协议一旦被张贴在</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">上即生效，并代替原来的协议。用户可随时登陆查阅最新协议；用户有义务不时关注并阅读最新版的协议及</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">公告。如用户不同意更新后的协议，可以且应立即停止接受</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">依据本协议提供的服务；如用户继续使用本</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">提供的服务的，即视为同意更新后的协议。</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">建议您在使用</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">之前阅读本协议及</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">的公告。</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">如果本协议中任何一条被视为废止、无效或因任何理由不可执行，该条应视为可分的且并不影响任何其余条款的有效性和可执行性。</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">&nbsp;</span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">7</span><span style="font-family:Helvetica; font-size:11pt">.2</span><span style="font-family:Helvetica; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">任何经</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">确认已经违反相关法律法规或本协议或</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">使用规则某一项或多项规定的用户，</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">有权决定是否给予暂停使用或终止使用的处理，且因此造成的一切后果由用户自行承担。</span>
            </p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">&nbsp;</span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">7</span><span style="font-family:Helvetica; font-size:11pt">.3</span><span style="font-family:Helvetica; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">客户与</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">基于交易合作签署的其他书面协议与本协议不一致的，以双方书面签署的协议为准。</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">&nbsp;</span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">第</span><span style="font-family:Helvetica; font-size:12pt; font-weight:bold">8</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">条</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:bold"> </span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">法律管辖和适用</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:bold"> </span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:11pt">本协议的订立、执行和解释及争议的解决均应适用在中华人民共和国大陆地区适用之有效法律（但不包括其冲突法规则）。</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">如发生本协议与适用之法律相抵触时，则这些条款将完全按法律规定重新解释，而其它有效条款继续有效。</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">如缔约方就本协议内容或其执行发生任何争议，双方应尽力友好协商解决；协商不成时，任何一方均可向有管辖权的中华人民共和国大陆地区法院提起诉讼。</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">&nbsp;</span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">第</span><span style="font-family:Helvetica; font-size:12pt; font-weight:bold">9</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">条</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:bold"> </span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:normal">其他</span><span style="font-family:'Arial Unicode MS'; font-size:12pt; font-weight:bold"> </span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">9</span><span style="font-family:Helvetica; font-size:11pt">.1</span><span style="font-family:Helvetica; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">所有者是指在政府部门依法许可或备案的淘不锈经营主体。</span><span style="font-family:'Arial Unicode MS'; font-size:11pt"> </span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">9</span><span style="font-family:Helvetica; font-size:11pt">.2</span><span style="font-family:Helvetica; font-size:11pt"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">尊重用户和消费者的合法权利，本协议及</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">上发布的各类规则、声明等其他内容，均是为了更好的、更加便利的为用户和消费者提供服务。</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">欢迎用户和社会各界提出意见和建议，淘不锈将虚心接受并适时修改本协议及</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">上的各类规则。</span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:11pt">&nbsp;</span>
            </p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:11pt; font-weight:normal">第</span><span style="font-family:Helvetica; font-size:11pt; font-weight:bold">10</span><span style="font-family:'Arial Unicode MS'; font-size:11pt; font-weight:normal">条</span><span style="font-family:'Arial Unicode MS'; font-size:11pt; font-weight:bold"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt; font-weight:normal">锁货</span><span style="font-family:'Arial Unicode MS'; font-size:11pt; font-weight:bold"> </span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:11pt">当前您在</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">下</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">的任何形式的买卖交易，</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">均不提供锁货功能，请在交易达成后尽快与对方进行细节沟通和</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">线下交易，</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">会尽力提供双方</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">线下交易的协助与协调工作。</span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">&nbsp;</span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:11pt; font-weight:normal">第</span><span style="font-family:Helvetica; font-size:11pt; font-weight:bold">11</span><span style="font-family:'Arial Unicode MS'; font-size:11pt; font-weight:normal">条</span><span style="font-family:'Arial Unicode MS'; font-size:11pt; font-weight:bold"> </span><span style="font-family:'Arial Unicode MS'; font-size:11pt; font-weight:normal">提货</span><span style="font-family:'Arial Unicode MS'; font-size:11pt; font-weight:bold"> </span></p>

            <p style="margin:0pt"><span style="font-family:'Arial Unicode MS'; font-size:11pt">当前您在</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">下</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">的任何形式的买卖交易，</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">均不提供</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">提货</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">相关功能，请在交易达成后尽快与对方进行细节沟通和</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">线下交易，</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">本平台</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">会尽力提供双方</span><span style="font-family:'Arial Unicode MS'; font-size:11pt">线下交易的协助与协调工作。</span></p>

            <p style="margin:0pt"><span style="font-family:Helvetica; font-size:11pt">&nbsp;</span></p>
        </div>
    </div>
</template>

<script>
    import { XHeader } from 'vux'
    export default {
        components: {
            XHeader
        },
        methods: {
            onBack(){
                this.$emit('on-back')
            }
        }
    }
</script>

<style lang="less" scoped>
    .popup-content{
        width: 100%;
        height: 100%;
        background-color: #fff;
    }
</style>


